<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>Diros</AssemblyName>
		<GenerateAssemblyInfo>False</GenerateAssemblyInfo>
		<TargetFramework>net472</TargetFramework>
		<LangVersion>11.0</LangVersion>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<RootNamespace />
	</PropertyGroup>
	<ItemGroup>
		<Reference Include="UnityEngine">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\Gorilla Tag\Gorilla Tag_Data\Managed\UnityEngine.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\Gorilla Tag\Gorilla Tag_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="Assembly-CSharp">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\Gorilla Tag\Gorilla Tag_Data\Managed\Assembly-CSharp.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="UnityEngine.PhysicsModule">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\Gorilla Tag\Gorilla Tag_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="0Harmony">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\Gorilla Tag\BepInEx\core\0Harmony.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="BepInEx">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\Gorilla Tag\BepInEx\core\BepInEx.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="Unity.InputSystem">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\Gorilla Tag\Gorilla Tag_Data\Managed\Unity.InputSystem.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>
</Project>
